<script setup lang="ts">
import { formatAdminDate } from "~/utils/format-date"
const PAGE_SIZE=25;const searchOffset=ref(0);const investigationOffset=ref(0);const q=ref("");const search=ref<any>();const criterion=ref("correlationId");const value=ref("");const investigation=ref<any>();const error=ref("")
const searchItems=computed(()=>search.value?.items??[])
const visibleSearch=computed(()=>searchItems.value.slice(searchOffset.value,searchOffset.value+PAGE_SIZE))
const investigationItems=computed(()=>investigation.value?.items??[])
const visibleInvestigation=computed(()=>investigationItems.value.slice(investigationOffset.value,investigationOffset.value+PAGE_SIZE))
async function runSearch(){searchOffset.value=0;error.value="";try{search.value=await $fetch('/api/provider/investigation/search',{query:{q:q.value,limit:100}})}catch(e:any){error.value=e?.data?.message??e?.statusMessage??e?.message}}
async function investigate(){investigationOffset.value=0;error.value="";try{investigation.value=await $fetch('/api/provider/investigation',{query:{[criterion.value]:value.value,limit:200}})}catch(e:any){error.value=e?.data?.message??e?.statusMessage??e?.message}}
</script><template><div class="page-stack"><div class="page-heading"><div><p class="eyebrow">INVESTIGATION</p><h1>IAM Investigation</h1><p>Discover IAM resources and correlate canonical activity.</p></div></div><section class="panel"><div class="panel-heading"><div><p class="eyebrow">UNIFIED SEARCH</p><h2>Find IAM resources</h2></div></div><div class="admin-filters"><input v-model="q" placeholder="Email, identity, membership, invitation, role or assignment" @keyup.enter="runSearch"><button class="secondary-button" @click="runSearch">Search</button></div><div v-if="search" class="table-wrap"><table><thead><tr><th>Type</th><th>Label</th><th>ID</th><th>Tenant</th><th>Status</th></tr></thead><tbody><tr v-for="item in visibleSearch" :key="`${item.type}:${item.id}`"><td>{{item.type}}</td><td>{{item.label}}</td><td class="mono">{{item.id}}</td><td class="mono">{{item.tenantId??'—'}}</td><td>{{item.status??'—'}}</td></tr></tbody></table></div><AppPagination v-if="search" :total="searchItems.length" :offset="searchOffset" :limit="PAGE_SIZE" @change="searchOffset=$event" /></section><section class="panel"><div class="panel-heading"><div><p class="eyebrow">CORRELATION</p><h2>Investigate activity</h2></div></div><div class="admin-filters"><select v-model="criterion"><option v-for="c in ['correlationId','requestId','actorId','tenantId','identityId','membershipId','invitationId']" :key="c">{{c}}</option></select><input v-model="value" placeholder="Exact identifier" @keyup.enter="investigate"><button class="secondary-button" @click="investigate">Investigate</button></div><div v-if="error" class="alert alert--error">{{error}}</div><div v-if="investigation" class="table-wrap"><table><thead><tr><th>Event</th><th>Occurred</th><th>Resource</th><th>Actor</th><th>Correlation</th></tr></thead><tbody><tr v-for="item in visibleInvestigation" :key="item.activityId"><td>{{item.eventType}}</td><td>{{formatAdminDate(item.occurredAt)}}</td><td class="mono">{{item.resource?.id}}</td><td class="mono">{{item.actorId??'—'}}</td><td class="mono">{{item.correlationId??'—'}}</td></tr></tbody></table></div><AppPagination v-if="investigation" :total="investigationItems.length" :offset="investigationOffset" :limit="PAGE_SIZE" @change="investigationOffset=$event" /></section></div></template>