name: local

variables:
  - name: baseUrl
    value: "http://127.0.0.1:3110"

  - name: administratorIdentityId
    value: "user_9624bfb8-d5f5-45e4-b2c7-c51a97596bd5"

  - name: administratorEmail
    value: "provider.admin@local.folksdo.test"

  - name: administratorSessionId
    value: "session_dcf8da8c-f67a-4ae3-a602-00ea5b636345"

  - name: administratorMembershipId
    value: "membership_b7e98ff92b1d448fa546be24e09d7fa8"

  - name: administratorTenantId
    value: "tenant_b7e98ff92b1d448fa546be24e09d7fa8"

  - name: ordinaryMemberIdentityId
    value: "user_7f554969-bdad-4177-b89b-402f1f77fae3"

  - name: ordinaryMemberSessionId
    value: "session_6f383a49-e2c7-4361-9649-03027c5229b8"

  - name: ordinaryMemberMembershipId
    value: "membership_81aae0b82e904072a453927b63bf9420"

  - name: ordinaryMemberTenantId
    value: "tenant_81aae0b82e904072a453927b63bf9420"
