<script setup lang="ts">
import { formatAdminDate } from "~/utils/format-date"
const { data: policy, status, error, refresh } = await useFetch<any>("/api/provider/configuration")
const tenantId = ref("")
const effective = ref<any>()
const effectiveError = ref("")
const saving = ref(false)
const saveError = ref("")
const saved = ref(false)
const form = reactive({ passwordSignInEnabled: true, maxActiveSessions: 8, sessionLifetimeMinutes: 60, emailVerificationRequired: true, defaultExpiryHours: 72, maxExpiryHours: 168, passwordRecoveryEnabled: true, recoveryRequestExpiryMinutes: 30, suspendRevokesSessions: true })
watch(policy, (value) => { if (!value) return; Object.assign(form, { passwordSignInEnabled:value.authentication.passwordSignInEnabled,maxActiveSessions:value.sessions.maxActiveSessions,sessionLifetimeMinutes:value.sessions.sessionLifetimeMinutes,emailVerificationRequired:value.verification.emailVerificationRequired,defaultExpiryHours:value.invitations.defaultExpiryHours,maxExpiryHours:value.invitations.maxExpiryHours,passwordRecoveryEnabled:value.recovery.passwordRecoveryEnabled,recoveryRequestExpiryMinutes:value.recovery.recoveryRequestExpiryMinutes,suspendRevokesSessions:value.security.suspendRevokesSessions }) }, { immediate:true })
async function save(){saving.value=true;saveError.value="";saved.value=false;try{await $fetch("/api/provider/configuration",{method:"PUT",body:{authentication:{passwordSignInEnabled:form.passwordSignInEnabled},sessions:{maxActiveSessions:Number(form.maxActiveSessions),sessionLifetimeMinutes:Number(form.sessionLifetimeMinutes)},verification:{emailVerificationRequired:form.emailVerificationRequired},invitations:{defaultExpiryHours:Number(form.defaultExpiryHours),maxExpiryHours:Number(form.maxExpiryHours)},recovery:{passwordRecoveryEnabled:form.passwordRecoveryEnabled,recoveryRequestExpiryMinutes:Number(form.recoveryRequestExpiryMinutes)},security:{suspendRevokesSessions:form.suspendRevokesSessions},tenantDelegation:policy.value?.tenantDelegation??{}}});saved.value=true;await refresh()}catch(e:any){saveError.value=e?.data?.message??e?.statusMessage??e?.message??"Policy update failed."}finally{saving.value=false}}
async function inspectEffective(){effectiveError.value="";effective.value=undefined;if(!tenantId.value.trim())return;try{effective.value=await $fetch(`/api/provider/configuration/effective/${encodeURIComponent(tenantId.value.trim())}`)}catch(e:any){effectiveError.value=e?.data?.message??e?.statusMessage??e?.message??"Effective policy lookup failed."}}
</script>
<template><div class="page-stack"><div class="page-heading"><div><p class="eyebrow">PLATFORM</p><h1>Configuration</h1><p>Provider-owned IAM business policy and tenant effective policy.</p></div></div><div v-if="status==='pending'" class="panel loading-panel">Loading IAM policy…</div><div v-else-if="error" class="panel error-panel"><strong>Configuration unavailable</strong><p>{{error.statusMessage}}</p></div><template v-else-if="policy"><section class="panel"><div class="panel-heading"><div><p class="eyebrow">PROVIDER POLICY</p><h2>{{policy.policyId}}</h2></div><span class="pill">Version {{policy.version}}</span></div><div class="policy-grid"><label><span>Maximum active sessions</span><input v-model.number="form.maxActiveSessions" type="number" min="1" max="100"></label><label><span>Session lifetime (minutes)</span><input v-model.number="form.sessionLifetimeMinutes" type="number" min="5"></label><label><span>Default invitation expiry (hours)</span><input v-model.number="form.defaultExpiryHours" type="number" min="1"></label><label><span>Maximum invitation expiry (hours)</span><input v-model.number="form.maxExpiryHours" type="number" min="1"></label><label><span>Recovery request expiry (minutes)</span><input v-model.number="form.recoveryRequestExpiryMinutes" type="number" min="5"></label></div><div class="toggle-grid"><label><input v-model="form.passwordSignInEnabled" type="checkbox"> Password sign-in enabled</label><label><input v-model="form.emailVerificationRequired" type="checkbox"> Email verification required</label><label><input v-model="form.passwordRecoveryEnabled" type="checkbox"> Password recovery enabled</label><label><input v-model="form.suspendRevokesSessions" type="checkbox"> Suspension revokes sessions</label></div><div v-if="saveError" class="alert alert--error">{{saveError}}</div><div v-if="saved" class="alert alert--success">Provider IAM policy updated.</div><div class="command-bar"><button class="secondary-button" :disabled="saving" @click="save">{{saving?'Saving…':'Save policy'}}</button><span class="muted">Updated {{formatAdminDate(policy.updatedAt)}} · {{policy.updatedBy}}</span></div></section><section class="panel"><div class="panel-heading"><div><p class="eyebrow">TENANT EFFECTIVE POLICY</p><h2>Inspect resolved policy</h2></div></div><div class="admin-filters"><input v-model="tenantId" placeholder="Tenant ID" @keyup.enter="inspectEffective"><button class="secondary-button" @click="inspectEffective">Inspect</button></div><div v-if="effectiveError" class="alert alert--error">{{effectiveError}}</div><template v-if="effective"><div class="result-meta"><span>Tenant <strong class="mono">{{effective.tenantId}}</strong></span><span>Provider version <strong>{{effective.providerPolicyVersion}}</strong></span><span>Tenant version <strong>{{effective.tenantPolicyVersion??'None'}}</strong></span></div><div class="policy-grid">
<label><span>Password sign-in</span><strong>{{effective.authentication.passwordSignInEnabled ? 'Enabled' : 'Disabled'}}</strong></label>
<label><span>Maximum active sessions</span><strong>{{effective.sessions.maxActiveSessions}}</strong></label>
<label><span>Session lifetime</span><strong>{{effective.sessions.sessionLifetimeMinutes}} minutes</strong></label>
<label><span>Email verification</span><strong>{{effective.verification.emailVerificationRequired ? 'Required' : 'Not required'}}</strong></label>
<label><span>Default invitation expiry</span><strong>{{effective.invitations.defaultExpiryHours}} hours</strong></label>
<label><span>Maximum invitation expiry</span><strong>{{effective.invitations.maxExpiryHours}} hours</strong></label>
<label><span>Password recovery</span><strong>{{effective.recovery.passwordRecoveryEnabled ? 'Enabled' : 'Disabled'}}</strong></label>
<label><span>Recovery request expiry</span><strong>{{effective.recovery.recoveryRequestExpiryMinutes}} minutes</strong></label>
<label><span>Suspension revokes sessions</span><strong>{{effective.security.suspendRevokesSessions ? 'Yes' : 'No'}}</strong></label>
</div></template></section></template></div></template>
